<?php
/**
 * Created by PhpStorm.
 * User: clementine
 * Date: 15/09/15
 * Time: 21:55
 */

namespace WebEvent\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends EntityRepository
{
}
