<?php
/**
 * Created by PhpStorm.
 * User: clementine
 * Date: 22/08/15
 * Time: 16:35
 */

namespace WebEvent\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceRepository extends EntityRepository
{
    /**
     * Retourne le lieu correspondant à l'id address
     */
    public function getPlaceByAddressId(int $id_address)
    {
        $place = $this->_em->getRepository('WebEventMainBundle:Place')->findBy(array('id' => $id_address));

        return $place;
    }

    /**
     * Retourne le lieu correspondant à l'id address
     */
    public function getPlacesByCityName($cityName)
    {
        $places = $this->_em->getRepository('WebEventMainBundle:Place')
            ->createQueryBuilder('p')
            ->select('p, a')
            ->join('p.address', 'a')
            ->where("a.ville LIKE :city")
            ->setParameter('city', '%'.$cityName)
            ->getQuery()
            ->execute();
        return $places;

    }
}
